# 锚点
pr: &pr {type: select, proxies: [🚀 节点选择, ♻️ 香港自动, ♻️ 日本自动, ♻️ 新加坡自动, ♻️ 美国自动, ♻️ 德国自动, ♻️ 英国自动, ♻️ 韩国自动, ♻️ 加拿大自动, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇺🇲 美国节点, 🇩🇪 德国节点, 🇬🇧 英国节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🌐 全部节点, ⭕ 自建节点, 🟢 直连]}

proxy-providers:
  Xboard:
    type: http
    interval: 1800
    path: ./providers/Xboard.yaml
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 🚀 节点选择
    url: "这里填你的 Xboard 订阅链接"
    override:
      skip-cert-verify: true
      udp: true
      down: "500 Mbps"
      up: "500 Mbps"

  gitlab:
    type: http
    interval: 1800
    path: ./providers/gitlab.yaml
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 🚀 节点选择
    url: "这里填你的 gitlab ClashMeta 订阅链接"
    override:
      skip-cert-verify: true
      udp: true
      down: "500 Mbps"
      up: "500 Mbps"

global-ua: clash.meta

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: warning

authentication:
  - "zszweb:这里换成新密码"

geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48

geox-url:
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb"
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  asn: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

external-controller: 0.0.0.0:9090
secret: "这里换成一个长随机密码"
external-ui: ui
external-ui-url: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"

tun:
  enable: true
  stack: mixed
  mtu: 9000
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "+.wan"
    - "+.local"
    - geosite:private
    - geosite:cn
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    "rule-set:private_domain,cn_domain":
      - 223.5.5.5
      - 119.29.29.29
    "rule-set:geolocation-!cn":
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query

proxies:
  - name: "🟢 直连"
    type: direct
    udp: true

proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [♻️ 香港自动, ♻️ 日本自动, ♻️ 新加坡自动, ♻️ 美国自动, ♻️ 德国自动, ♻️ 英国自动, ♻️ 韩国自动, ♻️ 加拿大自动, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇺🇲 美国节点, 🇩🇪 德国节点, 🇬🇧 英国节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🌐 全部节点, ⭕ 自建节点, 🟢 直连]}

  - {name: 📹 YouTube, <<: *pr}
  - {name: 🍀 Google, <<: *pr}
  - {name: 🤖 ChatGPT, <<: *pr}
  - {name: 👨🏿‍💻 GitHub, <<: *pr}
  - {name: 🧰 开发服务, <<: *pr}
  - {name: 🐬 OneDrive, <<: *pr}
  - {name: 🪟 Microsoft, <<: *pr}
  - {name: 🎵 TikTok, <<: *pr}
  - {name: 📲 Telegram, <<: *pr}
  - {name: 🎥 NETFLIX, <<: *pr}
  - {name: ✈️ Speedtest, <<: *pr}
  - {name: 💶 PayPal, <<: *pr}

  - {name: 🛑 广告拦截, type: select, proxies: [REJECT, 🟢 直连]}
  - {name: 🍎 Apple, type: select, proxies: [🟢 直连, 🚀 节点选择], url: http://connect.rom.miui.com/generate_204}
  - {name: 🎯 全球直连, type: select, proxies: [🟢 直连, 🚀 节点选择], url: http://connect.rom.miui.com/generate_204}
  - {name: 🐟 漏网之鱼, <<: *pr}

  - {name: ⭕ 自建节点, type: select, include-all: true, filter: "(?i)xboard|自建|home|zsz|vps"}
  - {name: 🇭🇰 香港节点, type: select, include-all: true, filter: "(?i)港|香港|hk|hongkong|hong kong"}
  - {name: 🇯🇵 日本节点, type: select, include-all: true, filter: "(?i)日|日本|jp|japan"}
  - {name: 🇸🇬 新加坡节点, type: select, include-all: true, filter: "(?i)新加坡|狮城|sg|singapore"}
  - {name: 🇺🇲 美国节点, type: select, include-all: true, filter: "(?i)美|美国|us|usa|united states|america"}
  - {name: 🇩🇪 德国节点, type: select, include-all: true, filter: "(?i)德|德国|de|germany"}
  - {name: 🇬🇧 英国节点, type: select, include-all: true, filter: "(?i)英|英国|uk|gb|united kingdom|britain"}
  - {name: 🇰🇷 韩国节点, type: select, include-all: true, filter: "(?i)韩|韩国|kr|korea"}
  - {name: 🇨🇦 加拿大节点, type: select, include-all: true, filter: "(?i)加拿大|ca|canada"}

  - {name: 🔊 googlVoiceProxy, type: select, include-all: true, filter: "(?i)google-us|gcp-us"}
  - {name: 📱 talktoneProxy, type: select, include-all: true, filter: "(?i)google-us|gcp-us"}
  - {name: 💳 bitgetProxy, type: select, proxies: [♻️ 日本自动, ♻️ 韩国自动, ♻️ 美国自动, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点]}

  - {name: ♻️ 香港自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)港|香港|hk|hongkong|hong kong", url: https://www.gstatic.com/generate_204}
  - {name: ♻️ 日本自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)日|日本|jp|japan", url: https://www.gstatic.com/generate_204}
  - {name: ♻️ 新加坡自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)新加坡|狮城|sg|singapore", url: https://www.gstatic.com/generate_204}
  - {name: ♻️ 美国自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)美|美国|us|usa|united states|america", url: https://www.gstatic.com/generate_204}
  - {name: ♻️ 德国自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)德|德国|de|germany", url: https://www.gstatic.com/generate_204}
  - {name: ♻️ 英国自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)英|英国|uk|gb|united kingdom|britain", url: https://www.gstatic.com/generate_204}
  - {name: ♻️ 韩国自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)韩|韩国|kr|korea", url: https://www.gstatic.com/generate_204}
  - {name: ♻️ 加拿大自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)加拿大|ca|canada", url: https://www.gstatic.com/generate_204}
  - {name: ♻️ 自动选择, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(直连)).)*$", url: https://www.gstatic.com/generate_204}

  - {name: 🌐 全部节点, type: select, include-all: true}

rules:
  - IP-CIDR,10.0.0.0/8,🟢 直连,no-resolve
  - IP-CIDR,172.16.0.0/12,🟢 直连,no-resolve
  - IP-CIDR,192.168.0.0/16,🟢 直连,no-resolve
  - IP-CIDR,127.0.0.0/8,🟢 直连,no-resolve

  - RULE-SET,private_domain,🟢 直连
  - RULE-SET,direct1,🟢 直连

  - RULE-SET,ads_domain,🛑 广告拦截

  - DOMAIN-SUFFIX,alicdn.com,🎯 全球直连
  - DOMAIN-SUFFIX,aliyuncs.com,🎯 全球直连
  - DOMAIN-SUFFIX,qq.com,🎯 全球直连
  - DOMAIN-SUFFIX,weixin.qq.com,🎯 全球直连
  - DOMAIN-SUFFIX,bdstatic.com,🎯 全球直连
  - DOMAIN-SUFFIX,baidu.com,🎯 全球直连
  - DOMAIN-SUFFIX,taobao.com,🎯 全球直连
  - DOMAIN-SUFFIX,tmall.com,🎯 全球直连
  - DOMAIN-SUFFIX,jd.com,🎯 全球直连
  - DOMAIN-SUFFIX,bilibili.com,🎯 全球直连
  - DOMAIN-SUFFIX,douyin.com,🎯 全球直连

  - RULE-SET,apple_domain,🍎 Apple
  - RULE-SET,proxylite,🚀 节点选择

  - RULE-SET,TaklatoneDirect,🟢 直连
  - RULE-SET,UKBankProxy,♻️ 英国自动
  - RULE-SET,DEBankProxy,♻️ 德国自动
  - RULE-SET,SGBankProxy,♻️ 新加坡自动

  - DOMAIN,lens.l.google.com,🔊 googlVoiceProxy
  - DOMAIN-SUFFIX,tktn.be,📱 talktoneProxy
  - DOMAIN-SUFFIX,bitget.fit,💳 bitgetProxy
  - DOMAIN-KEYWORD,wise,🇨🇦 加拿大节点

  - RULE-SET,ai,🤖 ChatGPT
  - RULE-SET,github_domain,🧰 开发服务
  - DOMAIN-SUFFIX,githubusercontent.com,🧰 开发服务
  - DOMAIN-SUFFIX,githubassets.com,🧰 开发服务
  - DOMAIN-SUFFIX,ghcr.io,🧰 开发服务
  - DOMAIN-SUFFIX,npmjs.org,🧰 开发服务
  - DOMAIN-SUFFIX,registry.npmjs.org,🧰 开发服务

  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET,google_domain,🍀 Google
  - RULE-SET,onedrive_domain,🐬 OneDrive
  - RULE-SET,microsoft_domain,🪟 Microsoft
  - RULE-SET,tiktok_domain,🎵 TikTok
  - RULE-SET,speedtest_domain,✈️ Speedtest
  - RULE-SET,telegram_domain,📲 Telegram
  - RULE-SET,netflix_domain,🎥 NETFLIX
  - RULE-SET,paypal_domain,💶 PayPal
  - RULE-SET,geolocation-!cn,🚀 节点选择
  - RULE-SET,cn_domain,🎯 全球直连

  - RULE-SET,google_ip,🍀 Google,no-resolve
  - RULE-SET,netflix_ip,🎥 NETFLIX,no-resolve
  - RULE-SET,telegram_ip,📲 Telegram,no-resolve
  - RULE-SET,cn_ip,🎯 全球直连

  - MATCH,🐟 漏网之鱼

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  qcy: &qcy {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}

rule-providers:
  private_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  ads_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs"}

  UKBankProxy: {<<: *class, url: "https://raw.githubusercontent.com/Nodewebzsz/Rule/refs/heads/main/UKbank.list"}
  DEBankProxy: {<<: *class, url: "https://raw.githubusercontent.com/Nodewebzsz/Rule/refs/heads/main/DEbank.list"}
  SGBankProxy: {<<: *class, url: "https://raw.githubusercontent.com/Nodewebzsz/Rule/refs/heads/main/SGbank.list"}
  TaklatoneDirect: {<<: *class, url: "https://raw.githubusercontent.com/Nodewebzsz/Rule/main/Taklatone.list"}

  direct1: {<<: *class, url: "https://gh.llkk.cc/https://raw.githubusercontent.com/qichiyuhub/rule/main/rules/direct.list"}
  proxylite: {<<: *class, url: "https://gh.llkk.cc/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/ProxyLite/ProxyLite.list"}
  ai: {<<: *class, url: "https://gh.llkk.cc/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/OpenAI/OpenAI.list"}

  youtube_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  speedtest_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  geolocation-!cn: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}

  cn_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
